site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        title: Switch to Dark Mode
      primary: green
      accent: light green
    - scheme: dark
      toggle:
        icon: material/toggle-switch
        title: Switch to Light Mode
      primary: teal
      accent: lime